# Generated by Django 3.2.6 on 2021-08-27 23:18

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210827_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='books',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='home.Book'),
        ),
    ]
